[build]
  command = "gatsby build"
  publish = "public/"

[template.environment]
  GATSBY_FLOTIQ_BASE_URL="https://api.flotiq.com"
  GATSBY_FLOTIQ_API_KEY="b9f33eea2eb6bce2b7c94d8855a1ea39"
  SNIPCART_API_KEY="YjUwMjdiY2EtYWM5YS00NWM5LTgxMTAtZjA4ZDk1MmJiODViNjM3Mjc2ODY1MzIxNTUzMDc4"
